name: Build micam-watcher

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build binaries
        run: |
          VERSION=${GITHUB_REF_NAME}
          mkdir -p dist
          cp config.example.json dist/
          cp micam-watcher.service dist/

          # Linux binary
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/micam-watcher-linux-${VERSION} ./cmd/micam-watcher          
          tar -czvf dist/micam-watcher-linux-${VERSION}.tar.gz -C dist micam-watcher-linux-${VERSION} config.example.json micam-watcher.service

          # Windows binary
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o dist/micam-watcher-windows-${VERSION}.exe ./cmd/micam-watcher
          zip dist/micam-watcher-windows-${VERSION}.zip dist/micam-watcher-windows-${VERSION}.exe config.example.json

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          prerelease: ${{ contains(github.ref, '-test') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
